apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teste
  template:
    metadata:
      labels:
        app: teste
    spec:
      containers:
      - name: teste
        image: teste:1.0.0
        ports:
        - containerPort: 80
